# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 21cbb28721df57356fefb6293d4f26ed14deeb5c638c6947c97153b221dd954983ae87f364d0f70a577177e8bea5aee7c8556ac96899be402ff7d93fa7663ba5

test:
  secret_key_base: 9667f25985675b9f34271a21f3609878c283e213f5d1af3dc782fd0f43a3057ca95ea78a0068e0500f2660797fddcf2d5e449612223afa01e0438ce5af3a88d3

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
